### ISSUE TITLE
Tabs - use native anchors

### ISSUE THREAD

**Issue by zemlanin** [wix/wix-ui-tpa#208] opened 2019-09-24 10:16 UTC
We made a TPA with `<Tabs>`. In it, each tab's `onClick` handler navigates to a tab-specific URL. It seems reasonable to expect that Cmd+click (or middle-mouse-button click; or right click + "Open in a new tab"; or whatever) should also be possible. It is not, because…

`<Tab>` component is [rendered](https://github.com/wix/wix-ui-tpa/blob/1f5ce19adcb485b4b8a43f044bfd1ec0b044ceda/src/components/Tabs/Tab/Tab.tsx#L52) as a `<span>`, we can't pass `href` and get most of native behavior (like Cmd+click to open link in a new tab) without re-implementing it in JS

As a possible fix, I see using `<a>` element instead of `<span>`  if `href` is in props

**Comment by jonathanadler** [comment] 2019-11-18 13:13
Hey @zemlanin 
That's an interesting issue.
However, the problem is that the Tabs components acts as a `tabpanel` and not (necessarily) as a navigation element.
That's the reason why we haven't used anchors - it isn't used to navigate between pages.
Maybe a `Menu` component (which is planned to be in the library) will suite you better?
If not, then we might need to check with the designers and our a11y advisor.

**Comment by zemlanin** [comment] 2019-11-18 14:18
> the Tabs components acts as a `tabpanel` and not (necessarily) as a navigation element

Line between `tabpanel` and "list of links" can be blurry. Like in [our case](https://antonve1.wixsite.com/mysite/search-results): click on a tab updates part of the page, but this part has a unique URL

> Maybe a `Menu` component (which is planned to be in the library) will suite you better?

I have no idea what goes/will go into `Menu`, so I don't know if it'll be better than `Tabs` 🤷‍♂

**Comment by jonathanadler** [comment] 2019-11-18 15:15
I see...
I would suggest asking your designer/product contact our designer team, and see which component will suite your needs best.
I'll email you their details

**Comment by jonathanadler** [comment] 2020-01-16 11:26
I'm closing this for now, as this is the intentional behaviour of the Tabs component

**Closed by jonathanadler** 2020-01-16 11:26 UTC
