### ISSUE TITLE
Usage of un-scoped elements.

### ISSUE THREAD

**Issue by barak007** [wix/wix-ui-tpa#600] opened 2021-01-13 09:36 UTC
https://github.com/wix/wix-ui-tpa/blob/5c54771c1fc5fb81b6a76b93cbf75ad0277324fe/src/components/Button/Button.st.css#L286

There is a `mobile` element in few selectors here but I think it should be `:mobile`

Do you have any build warnings?

**Comment by jonathanadler** [comment] 2021-01-13 12:42
duplicate of #601

**Closed by jonathanadler** 2021-01-13 12:42 UTC
